version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://postgres:postgres@postgres:5432/urlshortener
      REDIS_URL: redis://redis:6379
      BASE_URL: http://localhost:8000
      APP_ENV: local
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../app:/app/app

  ui:
    image: python:3.11-slim
    working_dir: /app
    command: >
      bash -c "pip install streamlit requests -q &&
               streamlit run streamlit_app/app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - ../:/app
    depends_on:
      - api

volumes:
  postgres_data:
