# FAST API URLs
[api]
base_url = "http://127.0.0.1:8000/"
create_short_url = "http://127.0.0.1:8000/create_short_code"
create_short_url_timeout = 10 # Always set this — without it a slow API hangs the app forever

#[postgres]
#host     = "localhost"
#port     = 5432
#dbname   = "myapp"
#user     = "postgres"
#password = "yourpassword"
